title: SCGAN
author: Songyao Jiang
theme: jekyll-theme-cayman
show_downloads: true
owner_name: Songyao Jiang
owner_url: songyaojiang.com
arxiv_link: https://arxiv.org/abs/1905.02320
youtube_link: https://www.youtube.com/watch?v=psGwpQsJA-0
slides_link: doc/SCGAN_FG21_slides.pdf